Updated text + added 'copy link' button
nimiq/browser-warning pull request #2
Opened 2019-12-10 00:49 UTC by svub

Reason: user got stuck in the "Uh oh, something went wrong" w/t knowing how to continue
Change: 
* Text with more concrete help (using browser names instead of the word "browser")
* A button to easily copy the link
* if trigger `navigator.share()` if available
Goal: help the user to overcome issue

2019-12-13 00:40 UTC, danimoh requested changes
![Screenshot](https://user-images.githubusercontent.com/6204514/70760287-c9c37900-1d0e-11ea-8773-833c91058e84.png)
I think the headline is too long. Also the button should probably be the last element.

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.html.template
> +            <pre></pre><button class="nq-button">Copy link</button>
What's the `<pre>` and the container for?

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.js
> +            $warningCopyLink.getElementsByTagName('button')[0].addEventListener('click', e => {
Use a normal `function` instead of an arrow function to avoid that old browsers can't parse this file.

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.js
> +                navigator.share(location.href);
See here for the correct api for `navigator.share`: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.js
> +            : null;
I think in the context of the browser warning we don't really need to keep the `originalRange` or refocus the `activeInput`. I would remove this logic to not bloat the file unnecessarily.

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.js
> +            $warningHeadline.textContent = 'Please copy the link and paste it directly in Safari, Chrome or Firefox.';
I would put Safari last.

2019-12-13 00:40 UTC, danimoh commented on dist/browser-warning.js
> +            $warningCopyLink.classList.add('show');
Instead of having the button already in the markup and requiring css to hide/unhide it, you could just create the button here when required.

2019-12-13 23:35 UTC, svub commented on dist/browser-warning.html.template
> +            <pre></pre><button class="nq-button">Copy link</button>
Oh, right, the idea was to actually show the URL. Wdyt is better: show the URL or remove those containers and just leave the button?

2019-12-13 23:39 UTC, svub commented on dist/browser-warning.js
> +                navigator.share(location.href);
Thank! Misread the parameter definition.

2019-12-16 12:48 UTC, sisou commented
Copying the link into another browser does not work. The Hub requires a referrer (for redirects) or a window reference from the opening website (for popups), both of which get lost when only copy-pasting the link into another browser/tab/instance.

The only solution here is to re-open the opening app (from which the Hub was launched) in another browser, not the Hub itself.

2019-12-17 03:12 UTC, danimoh commented
The browser warning is included in all our apps that use the hub.
Thus, the user will already get the warning before getting into the hub.
But third party developers might actually have that problem if they don't use our browser warnings.
Best would probably to display a different error if we're in the hub.

2020-01-19 01:26 UTC, danimoh requested changes

2020-01-19 01:26 UTC, danimoh commented on dist/browser-warning.js
> +                navigator.share({ data: location.href });
That's still wrong usage of `navigator.share`.

2020-01-19 01:26 UTC, danimoh commented on dist/browser-warning.js
> +    return showWarning('web-view');
Doesn't belong in the PR.

2020-01-23 23:07 UTC, danimoh commented on dist/browser-warning.js
> +                navigator.share({ data: location.href });
I fixed this

2020-01-23 23:07 UTC, danimoh commented on dist/browser-warning.js
> +    return showWarning('web-view');
I fixed this.

2020-01-24 16:29 UTC, danimoh approved these changes
I resolved the issues and additionally added the share button to all warnings. I also added a mechanism to adapt the warning / share behavior to be used in the hub.

2020-01-24 16:29 UTC, merged